##
## # Copyright (c) 2021 Facebook, inc. and its affiliates. All Rights Reserved
##
##
name: ui
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit  #=11.0
  - ipykernel  #=5.3.4
  - ipython  #=7.21.0
  - ipywidgets #=7.6.3
  - jedi #=0.17.2
  - jinja2 #=2.11.2
  - jupyter #=1.0.0
  - jupyterlab #=3.0.9
  - libjpeg-turbo
  - matplotlib #=3.3.2
  - mkl #=2020.2
  - ncurses #=6.2
  - nose #=1.3.7
  - numpy #=1.19.2
  - openssl #=1.1.1k
  - pandas #=1.2.1
  - pandoc #=2.11
  - pip #=20.3.3
  - prompt-toolkit
  - pygments #=2.7.4
  - pytest
  - python #=3.8.5
  - pytorch #=1.8.1
  - pyyaml #=5.4.1
  - qt #=5.9.7
  - qtconsole #=4.7.7
  - scikit-learn #=0.23.2
  - scipy #=1.5.2
  - seaborn #=0.11.1
  - sqlite #=3.33.0
  - submitit #=1.1.4
  - tabulate #=0.8.9
  - torchaudio
  - torchvision
  - tornado #=6.1
  - tqdm #=4.55.1
  - traitlets #=5.0.5
  - typing_extensions
  - yaml #=0.2.5
  - pip:
    - black #==20.8b1
    - blackcellmagic #==0.0.2
    - blessings #==1.7
    - click #==7.1.2
    - gpustat #==0.6.0
    - jupyter-contrib-core #==0.3.3
    - jupyter-contrib-nbextensions #==0.5.1
    - jupyter-highlight-selected-word #==0.2.0
    - jupyter-latex-envs #==1.4.6
    - jupyter-nbextensions-configurator #==0.4.1
    - lxml #==4.6.2
    - mypy-extensions #==0.4.3
    - nvidia-ml-py3 #==7.352.0
    - omegaconf #==2.0.6
    - parametrized #==0.1
    - pathspec #==0.8.1
    - pillow #==8.1.2
    - psutil #==5.8.0
    - gpytorch==1.3.1
    - filelock
