##
## # Copyright (c) 2021 Facebook, inc. and its affiliates. All Rights Reserved
##
##

sweep_dir: null
output_dir: null

dataset:
  nseeds: 1
  name: ImageNat
  partition: 'in'
  root: /checkpoint/ishmaelb/data/datasets/ILSVRC2012
  partitions_file: null
  equalize_partitions:  True
  seed: 0
  split: train
  batch_size: 256
  splits_props:
    train: 0.9
    eval: 0.1

algorithm:
  name: ERM
  nseeds: 1
  arch: resnet18
  use_mixed_precision: False
  seed: 0 # Mutable at dispatch
  sn: False
  sn_coef: 1.0
  sn_bn: False

slurm:
  preset: 'one_gpu'  # Key-value pairs below override presets.
  time: 10
  mem_per_gpu: '32G'
  cpus_per_task: 5
  partition: devlab
  array_parallelism: 512

experiment:
  distributed: False
  platform: slurm
  evaluate_every: 1
  checkpoint_every: 1
  num_epochs: 3
  ## ----- Mutable on the worker during distributed/device setup.
  output_dir: null
  seed: 42  # Workers seed
  device: 'cuda:0'
  rank: null
  local_rank: null
  world_size: null
  dist_protocol: null
  dist_url: null
  num_workers: 5
  # ------
