##
## # Copyright (c) 2021 Facebook, inc. and its affiliates. All Rights Reserved
##
##
sweep_dir: null
output_dir: null  # subfolder. Mutable at dispatch

dataset:
  nseeds: 3
  name: ImageNat
  partition: null  # Mutable at dispatch
  root: /checkpoint/ishmaelb/data/datasets/ILSVRC2012
  partitions_file: null
  equalize_partitions:  True
  seed: null # Mutable at dispatch
  split: train
  batch_size: 256
  splits_props:
    train: 0.9
    eval: 0.1

algorithm:
  nseeds: 5
  name: [ERM, Mixup, MCDropout, MIMO, RBF, SoftLabeler, DUE, RND, OC]
  arch: [resnet18]
  use_mixed_precision: True
  seed: null # Mutable at dispatch
  sn: [False, True]
  sn_coef: 1.0
  sn_bn: True


slurm:
  preset: 'distributed_8'  # Key-value pairs below override presets.
  time: 720
  mem_per_gpu: '32G'
  cpus_per_task: 5
  partition: learnfair
  array_parallelism: 512

experiment:
  distributed: True
  platform: slurm
  evaluate_every: 50
  checkpoint_every: 1
  num_epochs: 100
  ## ----- Mutable on the worker during distributed/device setup.
  output_dir: null
  seed: 42  # Workers seed
  device: 'cuda:0'
  rank: null
  local_rank: null
  world_size: null
  dist_protocol: null
  dist_url: null
  num_workers: 5
  # ------
